from .BindingDB import BindingDB
from .BioGRID import BioGRID
from .ChEMBL import ChEMBL
from .DIP import DIP
from .DOI import DOI
from .ELM import ELM
from .IntAct import IntAct
from .InterPro import InterPro
from .iPTMnet import iPTMnet
from .journal_article import JournalArticle
from .MINT import MINT
from .NCBI_Taxonomy import NCBI_Taxonomy
from .PDB import PDB
from .Pfam import Pfam
from .PhosphoSitePlus import PhosphoSitePlus
from .ProDom import ProDom
from .ProteinModelPortal import ProteinModelPortal
from .PubMed import PubMed
from .STRING import STRING
from .SUPFAM import SUPFAM
from .Swiss_Model import Swiss_Model
from .UniProtKB import UniProtKB

